-- =====================================================================
-- Mathematics Advanced — Subject Cloud
-- Shared backend for Supabase (PostgreSQL)
-- =====================================================================
-- Run this once in your Supabase project:  Dashboard → SQL Editor → New
-- query → paste this whole file → Run.
--
-- What it gives the static GitHub Pages site:
--   * shared student registration (username + password issued here, so two
--     students with the same first name never collide),
--   * shared visitor counter and per-day/per-file download counters,
--   * an admin-only export used by the dashboard and by the GitHub Action
--     that mirrors the register into data/cloud-data.json in the repository.
--
-- Security model
--   * Every table has Row Level Security enabled and NO policies, and direct
--     table privileges are revoked from the anon/authenticated roles. That
--     means the publishable key in the web page can read and write nothing on
--     its own.
--   * Everything the page is allowed to do goes through the SECURITY DEFINER
--     functions below, which validate their input, log events and increment
--     counters. Think of them as the API of this backend.
--   * Never put a secret key (sb_secret_… / service_role) in the web page or
--     in the repository. The publishable key (sb_publishable_… / legacy anon
--     JWT) is designed to be public.
-- =====================================================================

-- No extension is required: gen_random_uuid() is built into PostgreSQL 13+
-- (Supabase runs 15+), which keeps this script portable to any Postgres host.

-- ---------------------------------------------------------------- tables
create table if not exists public.madv_config (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);

insert into public.madv_config (key, value) values
  ('admin_user',            'peter82'),
  ('admin_pass',            'petgabs82'),
  ('open_registration',     'true'),
  ('roster_in_repo',        'true'),
  ('max_visits_per_day',    '5000'),
  ('max_downloads_per_day', '5000'),
  ('schema_version',        '1')
on conflict (key) do nothing;

-- One row per student. client_id is the id generated by the browser that
-- registered the student, so the same record can be found again offline.
create table if not exists public.madv_students (
  id             uuid primary key default gen_random_uuid(),
  client_id      text not null unique,
  first_name     text not null,
  username       text not null unique,
  password       text not null,
  year           text not null default '',
  status         text not null default 'active',
  notes          text not null default '',
  registered_at  timestamptz not null default now(),
  last_visit     timestamptz,
  visit_count    integer not null default 0,
  download_count integer not null default 0,
  updated_at     timestamptz not null default now(),
  constraint madv_students_status_check check (status in ('active', 'blocked'))
);
create index if not exists madv_students_username_idx on public.madv_students (lower(username));

-- Aggregate counters: 'visits', 'downloads'.
create table if not exists public.madv_counters (
  key        text primary key,
  value      bigint not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.madv_counters (key, value) values ('visits', 0), ('downloads', 0)
on conflict (key) do nothing;

-- One row per calendar day, used for the 14-day sparkline.
create table if not exists public.madv_daily (
  day        text primary key,
  visits     bigint not null default 0,
  downloads  bigint not null default 0,
  updated_at timestamptz not null default now()
);

-- Per-file download totals (mirrored onto each resource in the library).
create table if not exists public.madv_file_totals (
  resource_key     text primary key,
  total            bigint not null default 0,
  last_download_at timestamptz
);

-- Devices seen at least once = unique visitor count.
create table if not exists public.madv_devices (
  device_id  text primary key,
  first_seen timestamptz not null default now(),
  last_seen  timestamptz not null default now(),
  visits     bigint not null default 0
);

-- Idempotency for download events (a retry must not double count).
create table if not exists public.madv_download_events (
  event_id    text primary key,
  resource_key text not null,
  created_at  timestamptz not null default now()
);

-- Activity logs (bounded, read by the admin dashboard and the repo export).
create table if not exists public.madv_downloads (
  id           bigserial primary key,
  at           timestamptz not null default now(),
  student_id   text,
  student_name text,
  student_year text,
  resource_id  text,
  resource_key text,
  title        text,
  file_name    text,
  category     text,
  topic        text,
  year         text
);
create index if not exists madv_downloads_at_idx on public.madv_downloads (at desc);

create table if not exists public.madv_visits (
  id         bigserial primary key,
  at         timestamptz not null default now(),
  day        text not null,
  device_id  text,
  student_id text,
  name       text,
  year       text
);
create index if not exists madv_visits_at_idx on public.madv_visits (at desc);

create table if not exists public.madv_logins (
  id         bigserial primary key,
  at         timestamptz not null default now(),
  student_id text,
  name       text,
  year       text,
  ok         boolean not null default false,
  kind       text
);
create index if not exists madv_logins_at_idx on public.madv_logins (at desc);

-- ------------------------------------------------------------- utilities
create or replace function public.madv_config_bool(p_key text, p_default boolean)
returns boolean
language sql
stable
set search_path = public, pg_temp
as $$
  select coalesce(
    nullif((select value from public.madv_config where key = p_key), '')::boolean,
    p_default);
$$;

create or replace function public.madv_config_int(p_key text, p_default bigint)
returns bigint
language sql
stable
set search_path = public, pg_temp
as $$
  select coalesce(
    nullif((select value from public.madv_config where key = p_key), '')::bigint,
    p_default);
$$;

-- "Year 11" -> "11", used for the deterministic student password.
create or replace function public.madv_year_digits(p_year text)
returns text
language sql
immutable
set search_path = public, pg_temp
as $$
  select coalesce(regexp_replace(coalesce(p_year, ''), '[^0-9]', '', 'g'), '');
$$;

-- ------------------------------------------------------------ counters
create or replace function public.madv_bump_counter(p_key text, p_delta bigint)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_value bigint;
begin
  insert into public.madv_counters (key, value)
  values (p_key, greatest(p_delta, 0))
  on conflict (key) do update
    set value = madv_counters.value + greatest(p_delta, 0), updated_at = now()
  returning value into v_value;
  return coalesce(v_value, 0);
end;
$$;

-- ------------------------------------------------------------- madv_health
-- Used by the "Test connection" button in Cloud settings.
create or replace function public.madv_health()
returns jsonb
language sql
stable
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'ok', true,
    'provider', 'supabase',
    'schemaVersion', (select value from public.madv_config where key = 'schema_version'),
    'students', (select count(*) from public.madv_students),
    'time', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
  );
$$;

-- -------------------------------------------------------------- madv_stats
-- Public: totals only, never student details.
create or replace function public.madv_stats()
returns jsonb
language plpgsql
security definer
stable
set search_path = public, pg_temp
as $$
declare
  v_visits   bigint;
  v_downloads bigint;
  v_unique   bigint;
  v_daily    jsonb;
  v_files    jsonb;
begin
  select coalesce(value, 0) into v_visits   from public.madv_counters where key = 'visits';
  select coalesce(value, 0) into v_downloads from public.madv_counters where key = 'downloads';
  select count(*) into v_unique from public.madv_devices;

  select coalesce(jsonb_object_agg(day, jsonb_build_object('visits', visits, 'downloads', downloads)), '{}'::jsonb)
    into v_daily
    from (select day, visits, downloads from public.madv_daily order by day desc limit 60) d;

  select coalesce(jsonb_object_agg(resource_key,
           jsonb_build_object('total', total,
             'lastDownloadAt', to_char(last_download_at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))), '{}'::jsonb)
    into v_files
    from public.madv_file_totals;

  return jsonb_build_object(
    'ok', true,
    'visits', coalesce(v_visits, 0),
    'downloads', coalesce(v_downloads, 0),
    'uniqueVisitors', coalesce(v_unique, 0),
    'day', to_char(now() at time zone 'utc', 'YYYY-MM-DD'),
    'daily', v_daily,
    'perFile', v_files,
    'updatedAt', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
  );
end;
$$;

-- -------------------------------------------------------------- madv_visit
create or replace function public.madv_visit(
  p_device_id  text,
  p_day        text,
  p_student_id text default null,
  p_name       text default null,
  p_year       text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_recent timestamptz;
  v_visits bigint;
  v_unique bigint;
  v_cap    bigint;
  v_today  bigint;
begin
  if p_device_id is null or length(p_device_id) < 4 or length(p_device_id) > 60 then
    return jsonb_build_object('ok', false, 'error', 'A valid device id is required.');
  end if;
  if p_day is null or p_day !~ '^\d{4}-\d{2}-\d{2}$' then
    return jsonb_build_object('ok', false, 'error', 'A valid day (YYYY-MM-DD) is required.');
  end if;

  -- Anti-refresh guard: one counted visit per device (+ student) per 30 min.
  select max(at) into v_recent
    from public.madv_visits
   where device_id = p_device_id
     and coalesce(student_id, '') = coalesce(nullif(p_student_id, ''), '')
     and at > now() - interval '30 minutes';

  if v_recent is not null then
    select coalesce(value, 0) into v_visits from public.madv_counters where key = 'visits';
    select count(*) into v_unique from public.madv_devices;
    return jsonb_build_object('ok', true, 'visits', coalesce(v_visits, 0),
      'uniqueVisitors', v_unique, 'duplicate', true);
  end if;

  v_cap := public.madv_config_int('max_visits_per_day', 0);
  if v_cap > 0 then
    select coalesce(visits, 0) into v_today from public.madv_daily where day = p_day;
    if coalesce(v_today, 0) >= v_cap then
      return jsonb_build_object('ok', false, 'error', 'The daily visit limit has been reached.');
    end if;
  end if;

  insert into public.madv_visits (day, device_id, student_id, name, year)
  values (p_day, p_device_id, nullif(p_student_id, ''), nullif(p_name, ''), nullif(p_year, ''));

  insert into public.madv_devices (device_id, first_seen, last_seen, visits)
  values (p_device_id, now(), now(), 1)
  on conflict (device_id) do update
    set last_seen = now(), visits = madv_devices.visits + 1;

  v_visits := public.madv_bump_counter('visits', 1);

  insert into public.madv_daily (day, visits, downloads)
  values (p_day, 1, 0)
  on conflict (day) do update set visits = madv_daily.visits + 1, updated_at = now();

  select count(*) into v_unique from public.madv_devices;

  delete from public.madv_visits where at < now() - interval '180 days';

  return jsonb_build_object('ok', true, 'visits', v_visits, 'uniqueVisitors', v_unique);
end;
$$;

-- ----------------------------------------------------------- madv_download
-- p_payload keys: day, at, studentId, studentName, studentYear, resourceId,
--                 title, fileName, category, topic, year
create or replace function public.madv_download(
  p_event_id     text,
  p_resource_key text,
  p_payload      jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_day    text;
  v_total  bigint;
  v_file   bigint;
  v_last   timestamptz;
  v_cap    bigint;
  v_today  bigint;
begin
  if p_event_id is null or length(p_event_id) < 6 or length(p_event_id) > 80 then
    return jsonb_build_object('ok', false, 'error', 'A valid event id is required.');
  end if;
  if p_resource_key is null or length(p_resource_key) = 0 or length(p_resource_key) > 300 then
    return jsonb_build_object('ok', false, 'error', 'A valid resource key is required.');
  end if;

  -- Retries and duplicate clicks must not inflate the counter.
  if exists (select 1 from public.madv_download_events where event_id = p_event_id) then
    select total, last_download_at into v_file, v_last
      from public.madv_file_totals where resource_key = p_resource_key;
    select coalesce(value, 0) into v_total from public.madv_counters where key = 'downloads';
    return jsonb_build_object('ok', true, 'duplicate', true, 'total', coalesce(v_total, 0),
      'resourceKey', p_resource_key, 'resourceTotal', coalesce(v_file, 0),
      'lastDownloadAt', to_char(v_last at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
  end if;

  v_cap := public.madv_config_int('max_downloads_per_day', 0);
  v_day := coalesce(nullif(p_payload ->> 'day', ''), to_char(now() at time zone 'utc', 'YYYY-MM-DD'));
  if v_day !~ '^\d{4}-\d{2}-\d{2}$' then
    v_day := to_char(now() at time zone 'utc', 'YYYY-MM-DD');
  end if;

  if v_cap > 0 then
    select coalesce(downloads, 0) into v_today from public.madv_daily where day = v_day;
    if coalesce(v_today, 0) >= v_cap then
      return jsonb_build_object('ok', false, 'error', 'The daily download limit has been reached.');
    end if;
  end if;

  insert into public.madv_download_events (event_id, resource_key) values (p_event_id, p_resource_key);

  insert into public.madv_downloads (at, student_id, student_name, student_year,
      resource_id, resource_key, title, file_name, category, topic, year)
  values (
    coalesce((p_payload ->> 'at')::timestamptz, now()),
    nullif(p_payload ->> 'studentId', ''),
    nullif(p_payload ->> 'studentName', ''),
    nullif(p_payload ->> 'studentYear', ''),
    nullif(p_payload ->> 'resourceId', ''),
    p_resource_key,
    nullif(p_payload ->> 'title', ''),
    nullif(p_payload ->> 'fileName', ''),
    nullif(p_payload ->> 'category', ''),
    nullif(p_payload ->> 'topic', ''),
    nullif(p_payload ->> 'year', '')
  );

  -- Keep the student's own tally in step with the shared log.
  if nullif(p_payload ->> 'studentId', '') is not null then
    update public.madv_students
       set download_count = download_count + 1, last_visit = now(), updated_at = now()
     where client_id = p_payload ->> 'studentId';
  end if;

  v_total := public.madv_bump_counter('downloads', 1);

  insert into public.madv_daily (day, visits, downloads)
  values (v_day, 0, 1)
  on conflict (day) do update set downloads = madv_daily.downloads + 1, updated_at = now();

  insert into public.madv_file_totals (resource_key, total, last_download_at)
  values (p_resource_key, 1, now())
  on conflict (resource_key) do update
    set total = madv_file_totals.total + 1, last_download_at = now()
  returning total, last_download_at into v_file, v_last;

  delete from public.madv_download_events where created_at < now() - interval '180 days';

  return jsonb_build_object('ok', true, 'total', v_total, 'resourceKey', p_resource_key,
    'resourceTotal', coalesce(v_file, 0),
    'lastDownloadAt', to_char(v_last at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
end;
$$;

-- ----------------------------------------------------------- madv_register
-- Issues the username and password here so two students with the same first
-- name registering at the same moment cannot collide.
create or replace function public.madv_register(
  p_first_name text,
  p_year       text,
  p_client_id  text
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_base     text;
  v_username text;
  v_password text;
  v_name     text;
  v_row      public.madv_students;
  v_n        integer := 1;
begin
  v_name := btrim(regexp_replace(coalesce(p_first_name, ''), '\s+', ' ', 'g'));

  if not public.madv_config_bool('open_registration', true) then
    return jsonb_build_object('ok', false,
      'error', 'Self-registration is currently closed. Please ask your teacher to add you.');
  end if;
  if length(v_name) < 2 or length(v_name) > 30 or v_name !~* '^[A-Za-z][A-Za-z''\- ]*$' then
    return jsonb_build_object('ok', false,
      'error', 'Please enter the student''s first name (letters only, at least 2 characters).');
  end if;
  if coalesce(p_year, '') = '' or length(p_year) > 20 then
    return jsonb_build_object('ok', false, 'error', 'Please choose a year level.');
  end if;
  if p_client_id is null or length(p_client_id) < 4 or length(p_client_id) > 60 then
    return jsonb_build_object('ok', false, 'error', 'A valid client id is required.');
  end if;

  -- A retry with the same client id is idempotent, including a retry after
  -- the server committed but the browser did not receive the response.
  select * into v_row from public.madv_students where client_id = p_client_id;
  if found then
    return public.madv_student_json(v_row) || jsonb_build_object('ok', true, 'alreadyRegistered', true);
  end if;

  v_base := lower(regexp_replace(v_name, '[^a-zA-Z0-9]', '', 'g'));
  if v_base = '' then v_base := 'student'; end if;
  v_base := left(v_base, 24);

  -- A pre-check gives the common path a deterministic, readable username.
  -- The unique index remains the final arbiter; if two registrations race for
  -- the same suffix, retry with the next one rather than failing registration.
  loop
    v_username := case when v_n = 1 then v_base else v_base || v_n::text end;
    while exists (select 1 from public.madv_students where lower(username) = lower(v_username)) loop
      v_n := v_n + 1;
      if v_n > 500 then
        return jsonb_build_object('ok', false, 'error', 'Too many students share this name. Ask your teacher to add you.');
      end if;
      v_username := v_base || v_n::text;
    end loop;

    v_password := lower(v_username || public.madv_year_digits(p_year));
    begin
      insert into public.madv_students (client_id, first_name, username, password, year,
          status, registered_at, last_visit, visit_count, download_count)
      values (p_client_id, public.madv_titlecase(v_name), v_username, v_password, p_year,
          'active', now(), now(), 0, 0)
      returning * into v_row;
      exit;
    exception when unique_violation then
      -- A duplicate client id is a lost-response retry; a duplicate username
      -- means a concurrent student registered the same name first.
      select * into v_row from public.madv_students where client_id = p_client_id;
      if found then
        return public.madv_student_json(v_row) || jsonb_build_object('ok', true, 'alreadyRegistered', true);
      end if;
      v_n := v_n + 1;
      if v_n > 500 then
        return jsonb_build_object('ok', false, 'error', 'Too many students share this name. Ask your teacher to add you.');
      end if;
    end;
  end loop;

  insert into public.madv_logins (student_id, name, year, ok, kind)
  values (v_row.client_id, v_row.first_name, v_row.year, true, 'Registration');

  return public.madv_student_json(v_row) || jsonb_build_object('ok', true);
end;
$$;

-- -------------------------------------------------------------- madv_login
-- Verifies the password here, so the roster is never downloadable and a
-- wrong password cannot be compared against a leaked copy.
create or replace function public.madv_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.madv_students;
  v_user text := lower(btrim(coalesce(p_username, '')));
begin
  if v_user = '' then
    return jsonb_build_object('ok', false, 'error', 'Enter your username.');
  end if;

  select * into v_row from public.madv_students where lower(username) = v_user;

  if not found then
    insert into public.madv_logins (student_id, name, year, ok, kind)
    values (null, left(v_user, 40), '', false, 'Unknown username');
    return jsonb_build_object('ok', false,
      'error', 'No student found with that username. Register first, or ask your teacher to check the register.');
  end if;

  if v_row.status = 'blocked' then
    insert into public.madv_logins (student_id, name, year, ok, kind)
    values (v_row.client_id, v_row.first_name, v_row.year, false, 'Blocked account');
    return jsonb_build_object('ok', false,
      'error', 'This account has been blocked by the teacher. Please speak to your teacher.');
  end if;

  if v_row.password <> coalesce(p_password, '') then
    insert into public.madv_logins (student_id, name, year, ok, kind)
    values (v_row.client_id, v_row.first_name, v_row.year, false, 'Wrong password');
    return jsonb_build_object('ok', false, 'error',
      'That password does not match. The password is your username followed by your year number (for example ' ||
      v_row.username || public.madv_year_digits(v_row.year) || ').');
  end if;

  update public.madv_students
     set last_visit = now(), visit_count = visit_count + 1, updated_at = now()
   where id = v_row.id
  returning * into v_row;

  insert into public.madv_logins (student_id, name, year, ok, kind)
  values (v_row.client_id, v_row.first_name, v_row.year, true, 'Sign in');

  return public.madv_student_json(v_row) || jsonb_build_object('ok', true);
end;
$$;

-- ------------------------------------------------------ madv_student_json
create or replace function public.madv_student_json(p_row public.madv_students)
returns jsonb
language sql
immutable
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'id', p_row.id,
    'clientId', p_row.client_id,
    'firstName', p_row.first_name,
    'username', p_row.username,
    'password', p_row.password,
    'year', p_row.year,
    'status', p_row.status,
    'notes', p_row.notes,
    'registeredAt', to_char(p_row.registered_at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'lastVisit', to_char(p_row.last_visit at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'visitCount', p_row.visit_count,
    'downloadCount', p_row.download_count
  );
$$;

create or replace function public.madv_titlecase(p_text text)
returns text
language sql
immutable
set search_path = public, pg_temp
as $$
  select coalesce(
    (select string_agg(upper(left(w, 1)) || lower(substr(w, 2)), ' ')
       from regexp_split_to_table(btrim(coalesce(p_text, '')), '\s+') as w
      where w <> ''),
    '');
$$;

-- -------------------------------------------------------- madv_admin_check
create or replace function public.madv_admin_check(p_admin_user text, p_admin_pass text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.madv_config
     where key = 'admin_user' and value = coalesce(p_admin_user, '')
  ) and exists (
    select 1 from public.madv_config
     where key = 'admin_pass' and value = coalesce(p_admin_pass, '')
  );
$$;

-- ------------------------------------------------------- madv_admin_export
-- Full snapshot for the teacher dashboard and the GitHub Action. Requires the
-- administrator sign-in from Cloud settings (it is stored in the repository
-- secrets for the scheduled job, never in the page).
create or replace function public.madv_admin_export(
  p_admin_user text,
  p_admin_pass text,
  p_day        text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_students jsonb;
  v_logins   jsonb;
  v_downloads jsonb;
  v_visits   jsonb;
  v_daily    jsonb;
  v_visits_total bigint;
  v_downloads_total bigint;
  v_unique   bigint;
  -- The caller passes its own local day so "today" matches the site, not UTC.
  v_today    text := case when p_day ~ '^\d{4}-\d{2}-\d{2}$'
                          then p_day
                          else to_char(now() at time zone 'utc', 'YYYY-MM-DD') end;
begin
  if not public.madv_admin_check(p_admin_user, p_admin_pass) then
    return jsonb_build_object('ok', false, 'error', 'Administrator sign-in was not accepted.');
  end if;

  select coalesce(jsonb_agg(public.madv_student_json(s) order by s.registered_at), '[]'::jsonb)
    into v_students from public.madv_students s;

  select coalesce(jsonb_agg(jsonb_build_object(
           'at', to_char(l.at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           'studentId', l.student_id, 'name', l.name, 'year', l.year,
           'ok', l.ok, 'kind', l.kind) order by l.at desc), '[]'::jsonb)
    into v_logins from (select * from public.madv_logins order by at desc limit 400) l;

  select coalesce(jsonb_agg(jsonb_build_object(
           'at', to_char(d.at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           'studentId', d.student_id, 'studentName', d.student_name, 'studentYear', d.student_year,
           'resourceId', d.resource_id, 'resourceKey', d.resource_key, 'title', d.title,
           'fileName', d.file_name, 'category', d.category, 'topic', d.topic, 'year', d.year)
           order by d.at desc), '[]'::jsonb)
    into v_downloads from (select * from public.madv_downloads order by at desc limit 400) d;

  select coalesce(jsonb_agg(jsonb_build_object(
           'at', to_char(v.at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           'studentId', v.student_id, 'name', v.name, 'year', v.year) order by v.at desc), '[]'::jsonb)
    into v_visits from (select * from public.madv_visits order by at desc limit 400) v;

  select coalesce(jsonb_object_agg(day, jsonb_build_object('visits', visits, 'downloads', downloads)), '{}'::jsonb)
    into v_daily from (select day, visits, downloads from public.madv_daily order by day desc limit 60) d;

  select coalesce(value, 0) into v_visits_total from public.madv_counters where key = 'visits';
  select coalesce(value, 0) into v_downloads_total from public.madv_counters where key = 'downloads';
  select count(*) into v_unique from public.madv_devices;

  return jsonb_build_object(
    'ok', true,
    'updatedAt', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'config', jsonb_build_object(
      'openRegistration', public.madv_config_bool('open_registration', true),
      'rosterInRepo', public.madv_config_bool('roster_in_repo', true)
    ),
    'counters', jsonb_build_object(
      'visits', v_visits_total,
      'downloads', v_downloads_total,
      'uniqueVisitors', v_unique,
      'day', v_today,
      'visitsToday', coalesce((select visits from public.madv_daily where day = v_today), 0),
      'downloadsToday', coalesce((select downloads from public.madv_daily where day = v_today), 0),
      'daily', v_daily
    ),
    'students', v_students,
    'logins', v_logins,
    'downloads', v_downloads,
    'visits', v_visits
  );
end;
$$;

-- ------------------------------------------------------ madv_admin_student
-- p_action: 'upsert' (patch by clientId), 'delete' (by clientId)
create or replace function public.madv_admin_student(
  p_action     text,
  p_payload    jsonb,
  p_admin_user text,
  p_admin_pass text
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_client_id text;
  v_row       public.madv_students;
begin
  if not public.madv_admin_check(p_admin_user, p_admin_pass) then
    return jsonb_build_object('ok', false, 'error', 'Administrator sign-in was not accepted.');
  end if;

  v_client_id := coalesce(p_payload ->> 'clientId', p_payload ->> 'id');
  if v_client_id is null or v_client_id = '' then
    return jsonb_build_object('ok', false, 'error', 'A student id is required.');
  end if;

  if p_action = 'delete' then
    delete from public.madv_students where client_id = v_client_id;
    return jsonb_build_object('ok', true, 'deleted', true, 'clientId', v_client_id);
  end if;

  if p_action <> 'upsert' then
    return jsonb_build_object('ok', false, 'error', 'Unknown action.');
  end if;

  update public.madv_students set
      first_name = coalesce(nullif(p_payload ->> 'firstName', ''), first_name),
      username   = coalesce(nullif(p_payload ->> 'username', ''), username),
      password   = coalesce(nullif(p_payload ->> 'password', ''), password),
      year       = coalesce(nullif(p_payload ->> 'year', ''), year),
      status     = coalesce(nullif(p_payload ->> 'status', ''), status),
      notes      = coalesce(p_payload ->> 'notes', notes),
      visit_count = coalesce(nullif(p_payload ->> 'visitCount', '')::integer, visit_count),
      download_count = coalesce(nullif(p_payload ->> 'downloadCount', '')::integer, download_count),
      last_visit = coalesce((nullif(p_payload ->> 'lastVisit', ''))::timestamptz, last_visit),
      updated_at = now()
    where client_id = v_client_id
  returning * into v_row;

  if not found then
    return jsonb_build_object('ok', false,
      'error', 'That student is not in the shared register yet (they registered before the backend was connected).');
  end if;

  return public.madv_student_json(v_row) || jsonb_build_object('ok', true);
end;
$$;

-- ------------------------------------------------------- madv_admin_config
create or replace function public.madv_admin_config(
  p_patch      jsonb,
  p_admin_user text,
  p_admin_pass text
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  k text;
  v_count integer := 0;
begin
  if not public.madv_admin_check(p_admin_user, p_admin_pass) then
    return jsonb_build_object('ok', false, 'error', 'Administrator sign-in was not accepted.');
  end if;

  for k in select jsonb_object_keys(coalesce(p_patch, '{}'::jsonb)) loop
    if k in ('admin_user', 'admin_pass', 'open_registration', 'roster_in_repo',
             'max_visits_per_day', 'max_downloads_per_day') then
      insert into public.madv_config (key, value) values (k, left(coalesce(p_patch ->> k, ''), 200))
      on conflict (key) do update set value = left(coalesce(p_patch ->> k, ''), 200), updated_at = now();
      v_count := v_count + 1;
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'updated', v_count,
    'config', jsonb_build_object(
      'openRegistration', public.madv_config_bool('open_registration', true),
      'rosterInRepo', public.madv_config_bool('roster_in_repo', true)));
end;
$$;

-- --------------------------------------------------------- RLS & grants
-- Turn on Row Level Security everywhere and revoke direct table access. The
-- page can then only do what the functions above allow.
alter table public.madv_config           enable row level security;
alter table public.madv_students         enable row level security;
alter table public.madv_counters         enable row level security;
alter table public.madv_daily            enable row level security;
alter table public.madv_file_totals      enable row level security;
alter table public.madv_devices          enable row level security;
alter table public.madv_download_events  enable row level security;
alter table public.madv_downloads        enable row level security;
alter table public.madv_visits           enable row level security;
alter table public.madv_logins           enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;

grant usage on schema public to anon;

-- Public endpoints (counters, registration and sign-in).
grant execute on function public.madv_health() to anon;
grant execute on function public.madv_stats() to anon;
grant execute on function public.madv_visit(text, text, text, text, text) to anon;
grant execute on function public.madv_download(text, text, jsonb) to anon;
grant execute on function public.madv_register(text, text, text) to anon;
grant execute on function public.madv_login(text, text) to anon;

-- Administrator endpoints.
grant execute on function public.madv_admin_export(text, text, text) to anon;
grant execute on function public.madv_admin_student(text, jsonb, text, text) to anon;
grant execute on function public.madv_admin_config(jsonb, text, text) to anon;

-- PostgREST caches the schema; reload it so the new functions appear at once.
notify pgrst, 'reload schema';
